---
barometer:
  host: 172.17.0.1
  port: 5672
  plugin_connectivity:
    interface: eth0

plugins:
  - cpufreq
  - cpu
  - disk
  - ethstat
  - ipc
  - load
  - memory
  - numa
  - processes
  - df
  - uptime
  - network
  - interface
  - conntrack
