apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: sa
  labels:
    prometheus: sa
spec:
  replicas: 1
  version: v2.2.0-rc.1
  serviceAccountName: prometheus-sa
  serviceMonitorSelector:
    matchExpressions:
    - {key: sa-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: sa
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
  storage:
    class: ""
    selector: {}
    resources: {}
    volumeClaimTemplate:
      spec:
        storageClassName: sa
        resources:
          requests:
            storage: 2Gi
