apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: sa
  name: prometheus-sa
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 31900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: sa
